dist: trusty
sudo: required
language: bash
env:
  global:
  - TF_VERSION="0.12.19"
  - TFLINT_VERSION="0.13.4"
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-11/run.sh |
  bash
- sudo wget https://releases.hashicorp.com/packer/1.0.4/packer_1.0.4_linux_amd64.zip -O /tmp/packer.zip
- sudo unzip -d /usr/local/bin/ /tmp/packer.zip
script:
- packer --version
notifications:
  slack:
    rooms:
      secure: Hf3g8uWCUvd1Hst0rnVYcU67wE4LzFIS3j/9WmwSN3y4VTDj2VhvxfqRyVxy4Lyy7TLcIwxwN25tyhx5r5SycJGiZkf5PynnBLFwL9bJyeVeMi3jUq1WHOfAQGpPHEje6Ob5gq/Lm+eIfgrJzsvFxDfClrSAxVRS09B+Htyf60ZYn/AKxxwipHwQGMRRFvPIg8TQhjEQqHm/aJDrcF1N+ZyKizfs3daip/08/eNyQ9BVPDAzCO59jQjhk0gT+vbiOBjOnZrv0UUekKDyGsXz7hpeLJuSh66WaCLyKHx9/SID9QmC7poXEipprTD8Dj35J/vrplxXRWaGD6jhq3eofYS+Fp4CSDMWLstsq3MQ7wsPPicS9di1Bor85puahMp0C635HhztmgeCWZG3HHZgLkb19nFunQBjRXeHkRH+QafpBH95Bww+QjnOFthrVrLmCo9tVAgoT82mbp2hEFPt15WD8eQK94pYqsDccoA3L3/jQkzvrQaLNlNCkjaja8+sMnU2wMAvoqDmVo2jCwpbseas8qi/H9AS2AgLD6YWyrz74crH51kPBerRR/vn7WVf8ftaLMcsv/D1z2zJIMuWfkjSNnvAbELHo1EcDl2bmV+snpk+S5bHX5MOBPA1kUud20yCaYBasg6ktWVOZzWpxdLoltZ/Nl8IwNcjlecUa5M=
branches:
  only:
    - ansible-3
