---
- name: Update all packages to the latest version
  apt: "name='*' state=latest"
  tags: install

- name: Add APT key
  apt_key:
    id: E52529D4
    keyserver: keyserver.ubuntu.com
  tags: install

- name: Add  repository
  apt_repository:
    repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.0 multiverse
    state: present
  tags: install

- name: Install mongodb package
  apt:
    name: mongodb-org
    state: present
  tags: install

- name: Configure service supervisor
  systemd:
    name: mongod
    enabled: yes
    state: started
  tags: install
