---
- name: Deploy App
  hosts: app
  tasks:
    - name: Fetch the latest version of application code
      become: true
      become_user: ubuntu
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: "/home/{{ deploy_user }}/reddit"
        version: monolith
      notify: restart puma

    - name: bundle install
      become: true
      become_user: ubuntu
      bundler:
        state: present
        chdir: "/home/{{ deploy_user }}/reddit"

  handlers:
  - name: restart puma
    become: true
    systemd: name=puma state=restarted
