---
- name: Install MongoDB 3.2
  hosts: db
  become: true
  tasks:
  - name: Update all packages to the latest version
    apt: "name='*' state=latest"

  - name: Add APT key
    apt_key:
      id: E52529D4
      keyserver: keyserver.ubuntu.com

  - name: Add  repository
    apt_repository:
      repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.0 multiverse
      state: present

  - name: Install mongodb package
    apt:
      name: mongodb-org
      state: present

  - name: Configure service supervisor
    systemd:
      name: mongod
      enabled: yes
